# Generated by Django 6.0.1 on 2026-03-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True, verbose_name='Тикер')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('instrument_type', models.CharField(max_length=50, verbose_name='Тип инструмента')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Текущая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Финансовый инструмент',
                'verbose_name_plural': 'Финансовые инструменты',
                'db_table': 'instrument',
                'ordering': ['ticker'],
            },
        ),
    ]
