# Generated by Django 6.0.1 on 2026-03-09 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskapp', '0003_portfolioposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('trend', models.DecimalField(decimal_places=6, max_digits=10)),
                ('volatility', models.DecimalField(decimal_places=6, max_digits=10)),
                ('noise_level', models.DecimalField(decimal_places=6, max_digits=10)),
                ('time_horizon', models.PositiveIntegerField()),
                ('time_step', models.DecimalField(decimal_places=4, max_digits=10)),
                ('iterations_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='riskapp.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenario',
                'ordering': ['-created_at'],
            },
        ),
    ]
