# Generated by Django 6.0.1 on 2026-03-09 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskapp', '0004_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('expected_return', models.DecimalField(decimal_places=6, max_digits=12)),
                ('portfolio_volatility', models.DecimalField(decimal_places=6, max_digits=12)),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_drawdown', models.DecimalField(decimal_places=6, max_digits=12)),
                ('status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='riskapp.scenario')),
            ],
            options={
                'db_table': 'simulation_result',
                'ordering': ['-execution_time'],
            },
        ),
    ]
