# Generated by Django 6.0.1 on 2026-03-09 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskapp', '0005_simulationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('confidence_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('simulation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='riskapp.simulationresult')),
            ],
            options={
                'db_table': 'risk_metric',
                'ordering': ['metric_name'],
            },
        ),
    ]
