# Generated by Django 6.0.1 on 2026-03-11 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskapp', '0006_riskmetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioposition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.CheckConstraint(condition=models.Q(('current_price__gte', 0)), name='instrument_current_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('initial_value__gte', 0)), name='portfolio_initial_value_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='portfolioposition',
            constraint=models.UniqueConstraint(fields=('portfolio', 'instrument'), name='unique_portfolio_instrument'),
        ),
        migrations.AddConstraint(
            model_name='portfolioposition',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='portfolio_position_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='portfolioposition',
            constraint=models.CheckConstraint(condition=models.Q(('average_purchase_price__gte', 0)), name='portfolio_position_avg_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='riskmetric',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_level__gte', 0), ('confidence_level__isnull', True), _connector='OR'), name='risk_metric_confidence_level_gte_0_or_null'),
        ),
        migrations.AddConstraint(
            model_name='riskmetric',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_level__lte', 100), ('confidence_level__isnull', True), _connector='OR'), name='risk_metric_confidence_level_lte_100_or_null'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.CheckConstraint(condition=models.Q(('volatility__gte', 0)), name='scenario_volatility_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.CheckConstraint(condition=models.Q(('time_horizon__gt', 0)), name='scenario_time_horizon_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.CheckConstraint(condition=models.Q(('time_step__gt', 0)), name='scenario_time_step_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.CheckConstraint(condition=models.Q(('iterations_count__gt', 0)), name='scenario_iterations_count_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='simulationresult',
            constraint=models.CheckConstraint(condition=models.Q(('final_value__gte', 0)), name='simulation_result_final_value_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='simulationresult',
            constraint=models.CheckConstraint(condition=models.Q(('max_drawdown__gte', 0)), name='simulation_result_max_drawdown_gte_0'),
        ),
    ]
