# Generated by Django 6.0.1 on 2026-05-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskapp', '0021_tradeoperation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['ticker'], 'verbose_name': 'Financial instrument', 'verbose_name_plural': 'Financial instruments'},
        ),
        migrations.AlterField(
            model_name='instrument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='currency',
            field=models.CharField(max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='current_price',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Current price'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(max_length=50, verbose_name='Instrument type'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ticker',
            field=models.CharField(max_length=20, unique=True, verbose_name='Ticker'),
        ),
    ]
